#!/bin/bash

set -e

hex() {
  openssl rand -hex 4
}

# Setting the Defaults
USER_NAME=${USER_NAME:-ivonet}
USER_ID=${USER_ID:-1000}
GROUP_NAME=${GROUP_NAME:-${USER_NAME}}
GROUP_ID=${GROUP_ID:-1000}
SUDO_ACCESS=${SUDO_ACCESS:-false}
PASSWORD=${PASSWORD:-"putsafepasswordhere"}
PORT=${PORT:-4200}
USER_CSS=${USER_CSS:-"Normal:-/etc/shellinabox/options-enabled/00_White-On-Black.css,Reverse:+/etc/shellinabox/options-enabled/00+Black-on-White.css;Colors:+/etc/shellinabox/options-enabled/01+Color-Terminal.css,Monochrome:-/etc/shellinabox/options-enabled/01_Monochrome.css"}
SERVICE=${SERVICE:-/:LOGIN}
HOME_DIR=${HOME_DIR:-/home/${USER_NAME}}
USE_SSL=${USE_SSL:-false}

echo "Preparing container .."
COMMAND="/usr/bin/shellinaboxd --debug --no-beep --disable-peer-check -c /var/lib/shellinabox -p ${PORT} --user-css ${USER_CSS}"

COMMAND+=" -u ${USER_NAME}"
COMMAND+=" -g ${GROUP_NAME}"

if [ "${USE_SSL}" == "false" ]; then
  COMMAND+=" --disable-ssl --disable-ssl-menu"
fi

if [ "${SUDO_ACCESS}" == "true" ]; then
  echo "-----------------------------------------------------"
  echo "- Sudo access will be available"
  echo "-----------------------------------------------------"
  sudo="-G sudo"
else
  echo "-----------------------------------------------------"
  echo "- Sudo access will NOT be available"
  echo "-----------------------------------------------------"
  sudo=""
fi

if [ -z "$(getent group "${GROUP_NAME}")" ]; then
  /usr/sbin/groupadd -g "${GROUP_ID}" "${GROUP_NAME}"
fi

if [ -z "$(getent passwd "${USER_NAME}")" ]; then
  /usr/sbin/useradd -u "${USER_ID}" -g "${GROUP_ID}" -s "${SHELL}" -d "${HOME_DIR}" -m ${sudo} "${USER_NAME}"
  if [ "${PASSWORD}" == "putsafepasswordhere" ]; then
    PASSWORD=$(hex)
    echo "-----------------------------------------------------"
    echo "- Autogenerated password for user ${USER_NAME}: ${PASSWORD} -"
    echo "-----------------------------------------------------"
  fi
  echo "${USER_NAME}:${PASSWORD}" | /usr/sbin/chpasswd
  unset PASSWORD
fi

# profile config
if [ -f  "${HOME_DIR}/.profile" ]
then
  if ! grep -q "UserKnownHostsFile" "${HOME_DIR}/.profile"
  then
    echo 'export PS1="\u: \$(pwd)> "' >> "${HOME_DIR}/.profile"
    echo 'alias ssh="/usr/bin/ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"' >> "${HOME_DIR}/.profile"
  fi
else
  echo 'export PS1="\u: \$(pwd)> "' >> "${HOME_DIR}/.profile"
  echo 'alias ssh="/usr/bin/ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"' >> "${HOME_DIR}/.profile"
fi

# making sure the used space is owned by the shellinabox user
chown -R  "${USER_NAME}:${GROUP_NAME}" /var/lib/shellinabox/

for service in ${SERVICE}
do
  COMMAND+=" -s ${service}"
done


#TODO create list of users based on input fle

echo "Starting container .."
if [ "$@" = "shellinabox" ]; then
  echo "Executing: ${COMMAND}"
  exec ${COMMAND}
else
  echo "Not executing: ${COMMAND}"
  echo "Executing: ${@}"
  exec $@
fi
